name: openai_sasat
description: "Project Open AI By Sasat"

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  get: ^4.6.6
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
 
